### ISSUE TITLE
Chrome issue?

### ISSUE THREAD

**Issue by Radiotechniman** [RonnyWinkler/io.home-assistant.community#5]
I accidentally deleted the long-term key so i had to link Homey with HA again, for some reason Chrome would not let me and state "incorrect bla bla " but when I did the same with FireFox it worked without a problem, same URL and same key .. 

just thought i'd mention it

**Comment by RonnyWinkler** [comment]
Hi, I just tried changing the credentials in repair view. No issue with chrome.
Checked app settings page, too. I also was able to set the token without problems.

**Comment by RonnyWinkler** [comment]
I could not reproduce the issue. Please comment again if you can reproduce.

**Comment by Radiotechniman** [comment]
Will do, thanks
