### ISSUE TITLE
Button Identify instead button

### ISSUE THREAD

**Issue by makleso6** [RonnyWinkler/io.home-assistant.community#6]
Hello! I add HomeKit Aqara Hub M3 to homeassistant via HomeKit device
in homeassistant there are buttons with Identify and event (click)
but after adding to Homey via this plugin, there is no events, only Identify

![image](https://github.com/user-attachments/assets/86575c7c-ae33-49d9-b430-b58e39d3d6e0)
![image](https://github.com/user-attachments/assets/d73c36a1-d2e9-459e-a60f-5e67a876e37b)
<img width="692" alt="2024-09-10 в 11 41 33" src="https://github.com/user-attachments/assets/8ee1b744-2dbf-4fd3-8746-2ba107f05171">

**Comment by RonnyWinkler** [comment]
Please checn the entities povided by the HA device.
The "diagnostic" is just a button entity it seems. You can add it as button.
The "event" can be a button (suggested by the icon) or just an event. If it's a button, you ca also add it as button.
In this case:
- Add the button (below events) to Homey
- Go to Homey device settings and check the "add device buttons" checkbox. So you get the "identify" button added to your device.

If real events are used, you can only use the app flow trigger for events, because events are stateless.

**Comment by makleso6** [comment]
Thanks for reply
But I don't understand how add button from Events (naming ButtonEvent) to Homey
<img width="342" alt=" 2024-09-10 в 18 01 12" src="https://github.com/user-attachments/assets/801103cf-2e51-45a6-811b-b72ae4783dcf">
only Identify visible in app

`Go to Homey device settings and check the "add device buttons" checkbox. So you get the "identify" button added to your device.`
Sorry I can not find checkbox

**Comment by makleso6** [comment]
is it possible to add Event as button?

**Comment by RonnyWinkler** [comment]
Please check the HA device details:
- Which entities are used in the HA device?
- Is an event fired when pressings a button?
You can get these information in HA developer tools (states/events).
This way you can see what entities/events are used for the HA device.

For events, just use this trigger card in Homey to start a flow on an event. Events are stateless, that means there is no device/entity created for. It's just a message inside HA.

![grafik](https://github.com/user-attachments/assets/c2a47590-31e6-4d7d-841e-de1cc76353bf)

Fill in the event name and perhaps device id. It depends on th event. If you can't find the event in HA developer tools, you can create a flow with this card and leave blank all fields. Then write all tags from the card into one timeline entry. This way you can find the event name.

And please use the forum thread for questions, not Github ;-)
https://community.homey.app/t/app-pro-home-assistant-community-app/71477
There are already some examples for events (Hue buttons). Please search the thread or ask there, Thanks,

**Comment by makleso6** [comment]
Thanks!!
